-- AlterTable
ALTER TABLE "videos" ALTER COLUMN "iso_3166_1" DROP NOT NULL,
ALTER COLUMN "iso_639_1" DROP NOT NULL,
ALTER COLUMN "name" DROP NOT NULL,
ALTER COLUMN "size" DROP NOT NULL,
ALTER COLUMN "type" DROP NOT NULL,
ALTER COLUMN "official" DROP NOT NULL,
ALTER COLUMN "published_at" DROP NOT NULL;
