-- AlterTable
ALTER TABLE "translations" ALTER COLUMN "iso_3166_1" DROP NOT NULL,
ALTER COLUMN "iso_639_1" DROP NOT NULL,
ALTER COLUMN "name" DROP NOT NULL,
ALTER COLUMN "english_name" DROP NOT NULL,
ALTER COLUMN "data" DROP NOT NULL;
